### ISSUE TITLE
Create a 404 page

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#327] opened 2019-11-22 22:18 UTC
Right now pages on the site do not display a 404 page.  When users go to a page that doesn't exist, they should be presented with a 404 page rather than the current page they are presented with (see below).

![Screen Shot 2019-11-22 at 5.15.40 PM.png](https://images.zenhubusercontent.com/5c35178086008d0a2e1830d9/247caf5e-d040-44f5-9755-61fe51755361)

Things to consider for the 404 Page

- [ ] Include the header and footer so folks can find there way to the main site.
- [ ] Include a way for them to ask a librarian if they believe they have reached the page in error.
- [ ] Make it abundantly clear that they are on a 404 page.

**Comment by rosy1280** [comment] 2019-11-26 15:47
right now on the current site any URL that you go to that doesn't exist redirects to our 404 page which means that you can't see the URL you were trying to go to.  @kristianserrano to consider how to do this better than current website.  

Also we should consider creating a 404 page in the pattern library since this is something that other applications might need.

**Comment by kristianserrano** [comment] 2019-12-09 19:56
@rosy1280 I've created a 404 page in Cascade here:
https://cascade.emory.edu/entity/open.act?id=ec2af2f70ae720980494f5dd50c3f0b9&type=page

I've reached out to @jamesbiasemory to ask how we can implement this on the server.

Minor side note: I've noticed an extra paragraph being inserted at the beginning of `section-main-body`.
![Screen Shot 2019-12-09 at 2.50.57 PM.png](https://images.zenhubusercontent.com/5b870487d5262f371e9eac64/80ca4fba-7fb0-4df2-a022-19a49026c2fc)

**Comment by kristianserrano** [comment] 2019-12-12 20:00
@rosy1280 this is now ready for testing.
https://staging.libraries.emory.edu/this-url-does-not-exist.html

I created this in Cascade using the standard info page so that it would more easily integrate with the site in terms of header, footer, linking, etc. We can easily update the page content or even recreate it with a different page type.

Please let me know if you have any additional questions or concerns.

**Comment by rosy1280** [comment] 2019-12-16 21:13
@kristianserrano the 404 page appears on staging but not prod.

**Comment by kristianserrano** [comment] 2019-12-16 22:07
@rosy1280 James hadn't set it up for `prod.libraries.emory.edu`, but he got it working now.

We'll also have to change that same config when we launch with `libraries.emory.edu`. I'll create an issue to track that step.

**Comment by kristianserrano** [comment] 2019-12-17 20:58
@rosy1280 since the 404 page is actually created and available in prod.libraries.emory.edu, I suggest perhaps we close this issue and create a new issue under the Prep for Site Launch epic.

**Comment by jamesbiasemory** [comment] 2019-12-23 15:33
I can confirm.

**Closed** 2020-01-06 15:31 UTC
Labels: bug, question
