### ISSUE TITLE
Develop and implement a pattern library and design system based on design assets

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/Pattern-Library#225] opened 2018-11-27 18:50 UTC

**Comment by laurenhamel** [comment] 2019-05-14 14:04
Should this be an epic? I'm also wondering if this is a duplicate of #228 or if this should be a parent epic to it?

**Comment by nikdragovic** [comment] 2019-05-14 14:10
Definitely epic-level, but almost too big to be useful. We can discuss whether it's overly duplicative.

**Comment by libdgg** [comment] 2019-05-31 00:00
@kristianserrano @laurenhamel per our standup today (5/30) i'm going to close this issue as it was deemed too broad and duplicative.

**Closed by libdgg** 2019-05-31 00:00 UTC
Labels: question
